<random>: Improve binomial_distribution accuracy
microsoft/STL pull request #1531
Opened 2020-12-14 07:28 UTC by MattStephanson

Fixes #1530.
* For small mean, replaces Poisson approximation with exact waiting time method based on cumulative sum of exponential variates.
* Uses cheap but rigorous approximation of exit condition for fast return on first iteration.

2020-12-21 16:05 UTC, MattStephanson commented
BTW, for reference, the underlying algorithm is from ["Non-Uniform Random Variate Generation"](http://luc.devroye.org/rnbookindex.html), Luc Devroye, section X.4, "Second waiting time method".

2020-12-27 09:19 UTC, statementreply commented on stl/inc/random
> +                    std::min(_Par0._Mean, _Ty1{3.678794411714423216e-1} * _Par0._Px + _Ty1{6.32120558828557678e-1});
```suggestion
                    (_STD min)(_Par0._Mean, _Ty1{3.678794411714423216e-1} * _Par0._Px + _Ty1{6.32120558828557678e-1});
```

2020-12-27 09:19 UTC, statementreply commented on stl/inc/random
> +            return (_Sum > -_Par0._Logp1) ? static_cast<_Ty>(_Res - _Ty{1}) : _Par0._Tx;
Could this control flow be reordered to avoid comparing the final `_Sum` with `-_Par0._Logp1` twice and overcounting `_Res`?

2020-12-27 19:08 UTC, MattStephanson commented
> There is an inconsistency wrt `Rand` and `_Rand`

I think I'm going to restore the original version anyway, because `1.0 - _Par0._Mean` makes it impossible to return anything other than 0 when `_Par0._Mean < DBL_EPSILON`.

2021-01-09 03:23 UTC, StephanTLavavej reviewed
Looks good to me - the logic here is significantly beyond my experience so I really appreciate the PR. :heart_eyes_cat: I will push changes for 2 trivial things I noticed.

2021-01-09 03:23 UTC, StephanTLavavej commented on stl/inc/random
> +                    return 0;
We conventionally use braces for all control flow.

2021-01-09 03:23 UTC, StephanTLavavej commented on tests/std/tests/GH_001530_binomial_accuracy/test.cpp
> +        ++counts[static_cast<size_t>(dist(gen))];
Technically should include `<cstddef>`.

2021-01-09 03:28 UTC, StephanTLavavej approved these changes

2021-01-13 17:46 UTC, statementreply requested changes
The proposed change doesn't correctly handle the case that _n_ * (1-_p_) < 1.

When _p_ > 0.5, except for the small _n_ case, the original algorithm generates _B_(_n_, _p_) as _n_ - _B_(_n_, 1-_p_). See `binomial_distribution::param_type::_Init()`:

``` cpp
_Pp    = _Px < 0.5 ? _Px : (1.0 - _Px);
_Mean  = _Tx * _Pp;
```

and the `return` below:

```cpp
return _Par0._Px == _Par0._Pp ? _Res : static_cast<_Ty>(_Par0._Tx - _Res);
```

Test case:

```cpp
#include <cmath>
#include <iostream>
#include <random>
#include <vector>

using namespace std;

int main() {
    constexpr int it_max  = 10'000'000;
    constexpr int n       = 25;
    constexpr double mean = n - 0.99;
    constexpr double p    = mean / n;
    constexpr double var  = n * p * (1.0 - p);

    mt19937 gen;
    binomial_distribution<> dist(n, p);

    vector<int> counts(n + 1);
    for (int i = 0; i < it_max; ++i) {
        ++counts[static_cast<size_t>(dist(gen))];
    }

    double sample_mean = 0.0;
    for (size_t i = 1; i < counts.size(); ++i) {
        sample_mean += static_cast<double>(i) * counts[i];
    }
    sample_mean /= it_max;

    cout << "Expected mean: " << mean << endl
         << "Observed mean: " << sample_mean << endl;

    double sample_var = 0.0;
    for (size_t i = 0; i < counts.size(); ++i) {
        sample_var += counts[i] * pow(i - sample_mean, 2);
    }
    sample_var /= it_max - 1;

    cout << "Expected variance: " << var << endl
         << "Observed variance: " << sample_var << endl;

    return 0;
}
```

Pre-PR output:

```
Expected mean: 24.01
Observed mean: 24.0104
Expected variance: 0.950796
Observed variance: 0.988557
```

Post-PR output:

```
Expected mean: 24.01
Observed mean: 0.990254
Expected variance: 0.950796
Observed variance: 0.950525
```

(Sorry I missed this in my previous review)

2021-01-14 06:10 UTC, MattStephanson commented
@StephanTLavavej I've pushed a bugfix based on @statementreply's feedback after your approval.

2021-01-16 06:59 UTC, statementreply commented on tests/std/tests/GH_001530_binomial_accuracy/test.cpp
> +    assert(abs(sample_var / var - 1.0) < 0.01);
```suggestion
    assert(abs(sample_mean / mean - 1.0) < tol);
    assert(abs(sample_var / var - 1.0) < tol);
```

2021-01-16 07:05 UTC, MattStephanson commented on tests/std/tests/GH_001530_binomial_accuracy/test.cpp
> +    assert(abs(sample_var / var - 1.0) < 0.01);
🤦‍♂️

2021-02-06 02:42 UTC, StephanTLavavej approved these changes

2021-02-08 21:33 UTC, CaseyCarter approved these changes
FYI: I've pushed a merge with `main`, and updated the list of libcxx test skips to indicate that my guess that #1530 caused `std/numerics/rand/rand.dis/rand.dist.bern/rand.dist.bern.bin/eval.PR44847.pass.cpp` to fail was wrong.

2021-02-08 23:48 UTC, StephanTLavavej approved these changes

2021-02-12 22:36 UTC, merged

2021-02-12 22:37 UTC, StephanTLavavej commented
Thanks for noticing and fixing this accuracy bug! :dart: :dart: :dart: