<complex>: Fix complex exp(Inf) and exp(NaN)
microsoft/STL pull request #1584
Opened 2021-01-23 16:23 UTC by statementreply

Works towards #887.

2021-02-06 02:23 UTC, StephanTLavavej commented
/azp run

2021-02-06 02:43 UTC, StephanTLavavej commented
/azp run

2021-06-18 04:10 UTC, StephanTLavavej requested changes
Thanks for fixing this long-standing misbehavior! Please let me know if you'd like me to investigate how to make the code compatible with `/clr:pure` - I think that avoiding C++20 usage and dealing with the `float_control` warning should be sufficient, but I can verify that if you want.

2021-06-18 04:10 UTC, StephanTLavavej commented on stl/src/xlexp.cpp
> +        *px = 0.0L * y;
Why is this different from `xexp.cpp` which said `*px = _Xfe_underflow(y);`?

2021-06-18 04:10 UTC, StephanTLavavej commented on stl/src/xlexp.cpp
> +        *px = _LInf._Long_double * y;
Similarly, `xexp.cpp` said `*px = _Xfe_overflow(y);` - should this be consistent?

2021-06-23 13:31 UTC, statementreply commented on stl/src/xmath.hpp
> +#pragma float_control(except, on, push)
Guarded `#pragma float_control` by `#ifndef _M_CEE_PURE`.

2021-08-12 03:53 UTC, StephanTLavavej approved these changes

2021-08-12 04:02 UTC, StephanTLavavej commented
I've pushed a merge with `main` - it was surprisingly free of manual merge conflicts, despite code being added near a removed shouty banner.

2021-08-14 00:52 UTC, StephanTLavavej commented
I'm mirroring this to an MSVC-internal PR. It's totally fine to push changes for code review feedback, but please notify me in that case.

2021-08-14 05:00 UTC, StephanTLavavej commented
Had to push one more change to fix the internal build - the `/clr:pure` build uses `/std:c++14` so we have to avoid terse `static_assert`.

2021-08-14 05:01 UTC, StephanTLavavej approved these changes

2021-08-16 21:12 UTC, barcharcraz approved these changes
This does appear to implement advertised behavior, although I mostly checked only that it did not do anything non-conforming (mess with the polar(0,x) case). I observe that the changes to polar are not currently covered by tests, since even after this change the polar llvm tests can not be enabled. We need to make sure to remember to turn those on.

2021-08-17 00:30 UTC, merged

2021-08-17 00:32 UTC, StephanTLavavej commented
Thanks for fixing more of these complex bugs! :joy_cat: :lady_beetle: :tada: