`<vector>`: Correctly pass target size, not size change to ASan annotator
microsoft/STL pull request #2420
Opened 2021-12-14 19:48 UTC by cbezault

@joemmett experienced ASan errors while attempting to build and run the compiler under ASan after my ASan vector change.
Upon inspection of the failure point @CaseyCarter noticed that we were passing the change of the size to the ASan annotator guard instead of the absolute target size in both `_Resize` and `assign`.

Casey and I also would like to see more vector tests running with ASan turned on but it is difficult to insert `/fsanitize=address` into an arbitrary matrix because it currently only supports the default IDLs and clang-cl currently does not support debug flavors of the CRT.

2021-12-14 22:53 UTC, CaseyCarter requested changes

2021-12-14 22:53 UTC, CaseyCarter commented on stl/inc/vector
> +                _ASAN_VECTOR_EXTEND_GUARD(_Newsize);
All 48 runs of `GH_002030_asan_annotate_vector` pass for me if I revert this change, line 1293, and line 1951. I'd feel better if we add test coverage for all four of these holes and not just line 1409 that the Compiler team triggered.

2021-12-15 01:51 UTC, CaseyCarter approved these changes

2021-12-15 02:10 UTC, StephanTLavavej commented
I think we should consider renaming `_Asan_extend_guard`/`_ASAN_VECTOR_EXTEND_GUARD` since the "absolute size" usage is not obvious, especially when `_Modify_annotation`/`_ASAN_VECTOR_MODIFY` takes a relative size. However, that can be done in another PR.

2021-12-15 03:07 UTC, cbezault commented
Thanks for the quick review guys.

2021-12-15 03:09 UTC, cbezault commented
@StephanTLavavej I totally agree. I think I named it extend guard because I had gotten mixed up between refactors whether it took a new absolute size or a delta, which is exactly the same refactor that missed these three call sites.

2021-12-16 00:33 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

2021-12-17 03:33 UTC, merged

2021-12-17 03:33 UTC, StephanTLavavej commented
Thanks @cbezault, @joemmett, and @CaseyCarter for finding and fixing this bug! :lady_beetle: :white_check_mark: :heart_eyes_cat: