Implement LWG-3598 `system_category().default_error_condition(0)`
microsoft/STL pull request #2560
Opened 2022-02-11 13:38 UTC by fsb4000

Fixes #2552 

Should I add a remainder for moving the fix to syserror.cpp when we will be able to modify the file?

`cond.message()` == `"Операция успешно завершена."` on my PC.

it's definitely something else on your PC so I decided to test with `!=` the fallback.

2022-02-11 13:41 UTC, StephanTLavavej commented
> Should I add a reminder for moving the fix to syserror.cpp when we will be able to modify the file?

I think that a TRANSITION comment, a followup issue, or both, would be appropriate.

2022-02-11 14:16 UTC, fsb4000 commented
I looked at https://github.com/microsoft/STL/blob/bbd5dbaa61f192b393d12ea75a2dae1b8a014e7a/stl/src/syserror.cpp#L113-L194
and it seems generic error messages doesn't depend on locale.

2022-02-11 22:47 UTC, CaseyCarter requested changes

2022-02-11 22:47 UTC, CaseyCarter commented on stl/inc/system_error
>          } else {
There are enough lines in the `else` here that we lose symmetry; I think it would be more readable to early-return and outdent.

2022-02-12 03:17 UTC, CaseyCarter approved these changes

2022-02-15 23:39 UTC, StephanTLavavej approved these changes

2022-02-15 23:39 UTC, StephanTLavavej commented on tests/std/tests/Dev11_0493504_error_category_lifetime/test.cpp
> +    assert(error_code() == error_condition());
No change requested: Construction of these temporaries could use empty braces, but it's not worth resetting testing for such a minor style issue in test code.

2022-02-17 09:48 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed. (I'll handle verifying that this works with the recent LLVM update.)

2022-02-18 02:00 UTC, merged