Implement LWG-3618 Unnecessary `iter_move` for `transform_view::iterator`
microsoft/STL pull request #2566
Opened 2022-02-13 15:17 UTC by fsb4000

Fixes #2554

2022-02-14 22:01 UTC, CaseyCarter approved these changes

2022-02-15 04:17 UTC, StephanTLavavej requested changes

2022-02-15 04:17 UTC, StephanTLavavej commented on stl/inc/ranges
> +                _NOEXCEPT_IDL0(noexcept(_STD invoke(*_Parent->_Fun, *_Current))) {
Previously, the Standard didn't mention `noexcept`, so we were free to partially strengthen it.

Now, the Standard mandates `noexcept(noexcept(invoke(*parent_->fun_, *current_)))`, so partially weakening it with `_NOEXCEPT_IDL0` is nonconformant.

I believe we need to say plain `noexcept` here. I'm not sure whether the function body needs to change. I also believe that the test needs to be updated:
https://github.com/microsoft/STL/blob/afe0800cd6bf0d163bf678ad4e1feb3c130d1ec5/tests/std/tests/P0896R4_views_transform/test.cpp#L489-L499

2022-02-15 23:54 UTC, StephanTLavavej requested changes

2022-02-15 23:54 UTC, StephanTLavavej commented on stl/inc/ranges
> +                }
In product code, we never use `try`/`catch` directly - it always has to be `_TRY_BEGIN`/`_CATCH_ALL`/`_CATCH_END` in order to respect `_HAS_EXCEPTIONS=0`, e.g.:
https://github.com/microsoft/STL/blob/afe0800cd6bf0d163bf678ad4e1feb3c130d1ec5/stl/inc/future#L473-L479

However, should we be try-catching at all here? I observe that `filter_view` marks `_Check_dereference()` as `noexcept`. Should we simply do the same for `transform_view`, and allow exceptions emitted from `_RANGES end(_Parent->_Range)` to slam into `noexcept`? The implementations are identical aside from error messages:

https://github.com/microsoft/STL/blob/afe0800cd6bf0d163bf678ad4e1feb3c130d1ec5/stl/inc/ranges#L1634-L1639
https://github.com/microsoft/STL/blob/afe0800cd6bf0d163bf678ad4e1feb3c130d1ec5/stl/inc/ranges#L1912-L1917

2022-02-16 06:58 UTC, fsb4000 commented
Yes, I agree that `filter_view::_Check_dereference` and `transform_view::_Check_dereference` should be the same.

Also do we still need to mark the LWG with `ranges` label?

2022-02-16 22:48 UTC, CaseyCarter approved these changes

2022-02-16 23:55 UTC, StephanTLavavej approved these changes

2022-02-16 23:59 UTC, StephanTLavavej commented
Thanks, this looks great. Unfortunately, the CLA bot was stuck, and although it's been fixed, this has affected all PRs which had pushed commits during a certain window. @fsb4000, apologies for the headache, but can you please close this PR and open a new one, which should allow the license/cla check to pass?

2022-02-17 09:49 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed. (I'll handle verifying that this works with the recent LLVM update.)

2022-02-17 10:21 UTC, StephanTLavavej commented
I've pushed an update to the libcxx skips, as deref and `iter_move` are now guaranteed noexcept.

2022-02-17 12:57 UTC, StephanTLavavej approved these changes

2022-02-17 18:12 UTC, CaseyCarter approved these changes

2022-02-18 02:09 UTC, merged

2022-02-18 02:10 UTC, StephanTLavavej commented
Thanks for transforming the STL to implement this LWG issue! :tada: :joy_cat: :smile_cat: