Add scripts to set the environment up to use just-built artifacts
microsoft/STL pull request #2578
Opened 2022-02-17 22:06 UTC by barcharcraz

These are intended for development,
because I kept forgetting to add in the arch prefix

This is a github-only change, there's nothing that will touch the internal build, and
the files are copied over outside the "output" directory.

2022-02-17 22:18 UTC, CaseyCarter approved these changes

2022-02-17 22:41 UTC, StephanTLavavej requested changes
Thanks - these scripts will make life more convenient.

2022-02-17 22:41 UTC, StephanTLavavej commented on stl/set_environment.bat.in
> +@set PATH="%~dp0out\bin\@VCLIBS_I386_OR_AMD64@;%PATH%"
Can you add copyright/license banners to these files? For `bat`, `::` works for comments.

2022-02-17 22:41 UTC, StephanTLavavej commented on stl/set_environment.bat.in
> +@set LIB="%~dp0\out\lib\@VCLIBS_I386_OR_AMD64@;%LIB%"
Unlike `%~dp0out` above, `%~dp0\out` adds an extra backslash here.

2022-02-17 23:38 UTC, StephanTLavavej approved these changes

2022-02-17 23:38 UTC, StephanTLavavej commented
Verified that both the BAT and PS1 produce the same paths that my local incantations do. FYI @CaseyCarter as significant changes were pushed.

2022-02-22 21:26 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

2022-02-23 01:21 UTC, merged

2022-02-23 01:21 UTC, StephanTLavavej commented
Thanks again for this quality-of-life improvement! :smile_cat: :tada: :rocket: