`<xstring>`: Restrict enabled `hash` specializations as required by the standard
microsoft/STL pull request #2741
Opened 2022-05-26 06:11 UTC by frederick-vs-ja

Fixes #757. Perhaps libcxx tests are enough.

I also move `_Is_EcharT` to `<xstring>` because I think its usage may be more general.

2022-05-26 08:20 UTC, fsb4000 commented
failed `tests/Dev09_172666_tr1_tuple_odr`

Same thing. I ran into the issue yesterday: https://github.com/microsoft/STL/pull/2739#issuecomment-1137793045

```c++
template <class>
_INLINE_VAR constexpr bool _Is_EcharT = false;
template <>
_INLINE_VAR constexpr bool _Is_EcharT<char> = true;
```
gives `fatal error LNK1169: one or more multiply defined symbols found` with clang-cl and C++14.
because `_INLINE_VAR` is nothing in C++14.

2022-05-26 16:09 UTC, CaseyCarter requested changes
I agree the existing test coverage suffices.

2022-05-26 16:09 UTC, CaseyCarter commented on stl/inc/xstring
>  template <class _Elem, class _Traits>
We should remove all occurrences of `_Traits` from this template, as well as the `is_same_v<_Traits, ...` constraint, and let the default template argument handle the traits type for us.

2022-05-26 16:09 UTC, CaseyCarter commented on stl/inc/xstring
>  template <class _Elem, class _Traits, class _Alloc>
Similarly, we should remove the `class _Traits` template parameter here and replace occurrences with `char_traits<_Elem>`.

2022-05-26 18:22 UTC, CaseyCarter approved these changes

2022-05-27 01:01 UTC, StephanTLavavej approved these changes

2022-06-01 03:35 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

2022-06-01 05:30 UTC, StephanTLavavej commented
This breaks the compiler backend with:

```
   643>D:\msvc\binaries\x86chk\inc\unordered_map(50,99): error C2280: 'std::_Uhash_compare<_Kty,_Hasher,_Keyeq>::_Uhash_compare(const std::_Uhash_compare<_Kty,_Hasher,_Keyeq> &)': attempting to reference a deleted function [D:\msvc\src\vctools\Compiler\Utc\build\arm64\utc-arm64.nativeproj]
                 with
                 [
                     _Kty=std::basic_string<char,std::char_traits<char>,UtcPoolAllocator<T_ALLOC,char>>,
                     _Hasher=std::hash<std::basic_string<char,std::char_traits<char>,UtcPoolAllocator<T_ALLOC,char>>>,
                     _Keyeq=std::equal_to<void>
                 ]
             explicit _Umap_traits(const _Tr& _Traits) noexcept(is_nothrow_copy_constructible_v<_Tr>) : _Tr(_Traits) {}
                                                                                                           ^
```

This isn't necessarily blocking (we could change the backend to use a custom hash), but it indicates that this change will be highly breaking.

I think we should speculatively implement LWG-3705 "Hashability shouldn't depend on `basic_string`'s allocator" here, now that @CaseyCarter's newly filed issue has a number. I'll validate and push changes to avoid having to drop this from the mirror PR.

2022-06-01 05:39 UTC, StephanTLavavej approved these changes

2022-06-02 00:38 UTC, merged

2022-06-02 00:39 UTC, StephanTLavavej commented
Thanks for improving conformance here and fixing these libcxx skips! :tada: :heart_eyes_cat: :white_check_mark:

2022-06-05 18:26 UTC, CaseyCarter reviewed
For posterity: this is my late approval of STL's final changes, which are exactly how I'd planned to implement LWG-3705.