Make integers unsigned and remove unneeded decrement
microsoft/STL pull request #3095
Opened 2022-09-09 14:52 UTC by AtariDreams

2022-09-09 16:33 UTC, AtariDreams commented
This doesn't work because qh is reassigned anyway. So the assignment does nothing.

2022-09-09 17:45 UTC, fsb4000 commented
Yes, I agree. 
godbolt.org generates the same assembly with `--qh;` and without `--qh;`.

But it generates 8 extra instructions with `unsigned int`: https://godbolt.org/z/cj56a4h6s

2022-09-09 22:41 UTC, StephanTLavavej requested changes

2022-09-09 22:41 UTC, StephanTLavavej commented on stl/src/multprec.cpp
> +    for (unsigned int i = 0; i < m + n + 1; ++i) {
The correctness of the `int` => `unsigned int` change seems reasonably easy to verify, but I don't believe that this is a clear improvement, and @fsb4000 has found potential negative codegen impact. Although I have a slight preference for unsigned types in general, I don't see sufficient value in changing this existing code, so I believe these changes should be dropped.

2022-09-09 22:41 UTC, StephanTLavavej commented on stl/src/multprec.cpp
> -            --qh;
No change requested, noting for other reviewers: This is safe because `qh` is a loop-local variable on line 131.

2022-09-14 02:29 UTC, StephanTLavavej commented
@AtariDreams We've asked you a few times to please avoid force-pushing commits after review has started, as this makes it harder to see what's changed. Is there some tool or part of your workflow that's doing this?

2022-09-14 13:01 UTC, AtariDreams commented
No, I apologize. I will refrain from doing this.

2022-09-20 16:36 UTC, AtariDreams commented
Okay so I was able to reduce the number of instructions even further from the original

2022-09-21 16:01 UTC, AtariDreams commented
@StephanTLavavej Ready!

2022-09-23 13:34 UTC, AtariDreams commented
Since the focus of this PR has changed. I will close it and reopen it as a new one.

2022-09-23 13:34 UTC, closed without merging