Miscellaneous Cleanups
microsoft/STL pull request #3178
Opened 2022-10-25 17:31 UTC by CaseyCarter

Mostly things I noticed while reviewing the last import batch at the last minute that were not worth resetting testing for, but does include a couple of "old" changes as well.

Separate commits to ease review:
* "`basic_string::_Move_construct_from_substr` already knows the allocator": avoids passing an allocator to this member function which can simply retrieve the stored allocator.
* "Consistently guard `_Verify_offset(-n)` against `-INT_MIN`" (in `<ranges>`): we had a couple of places that guarded against overflow negating the argument to `_Verify_offset`, we should do so consistently.
* "Cleanup `_NOEXCEPT_IDL0`": Removes this variation in `noexcept` between debug and release builds - it was a terrible idea. Make `transform_view::iterator::_Verify_offset` always `noexcept` by avoiding checks when the underlying iterator doesn't support `_Verify_offset`. Make that function and `elements_view::iterator::_Verify_offset` available only when `_IDL != 0` ***fixing a bug in `elements_view::iterator` that disabled the check***. Remove the now unused `_NOEXCEPT_IDL0` machinery. Fixes #1269.
* "Keep type and data member definitions together in `<execution>`": Fixes #330.
* "`<system_error>`: Correct `if (!cond) x(); else y()`": ... to `if (cond) y(); else x();`. Drive-by: Let's `static_assert` only when running the test suite.
* "`tests/P2278R4_basic_const_iterator` nitpicks":
  * Simplify nested requirement in `HasPeek`
  * Remove excess empty line
* "`tests/P2322R6_ranges_alg_fold`: factor out non-dependent tests": ... from the dependent test cases in `instantiator::call`. Reduces compile + run time by 27%.

2022-10-25 17:59 UTC, strega-nil-ms approved these changes
LGTM! (obviously, fix the red cross)

2022-10-25 18:05 UTC, StephanTLavavej requested changes

2022-10-25 18:13 UTC, StephanTLavavej approved these changes

2022-10-25 18:15 UTC, StephanTLavavej commented
I've pushed a commit to fix the test failures because `_STL_INTERNAL_STATIC_ASSERT` doesn't take a reason (maintainers are expected to know the reason through their psychic debugging powers :joy_cat:).

Additionally, I split it into two static assertions, partially to make things line up nicer, but also to follow our usual guidance to assert X and Y separately instead of `X && Y` (so if it ever fails, we can immediately see why), even though this is admittedly at very low risk of ever failing.

2022-10-25 18:30 UTC, CaseyCarter commented on stl/inc/system_error
>          "Unsupported platform");
🤦

2022-10-25 18:43 UTC, StephanTLavavej approved these changes

2022-10-25 19:31 UTC, CaseyCarter commented
/azp run

2022-10-25 19:34 UTC, CaseyCarter commented on tests/std/tests/P0896R4_views_transform_death/test.cpp
>  }
You meant to back this out.

2022-10-25 20:17 UTC, StephanTLavavej approved these changes

2022-10-25 23:26 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

2022-10-26 13:16 UTC, merged

2022-10-26 13:17 UTC, StephanTLavavej commented
Thanks for finding and fixing these issues! :derelict_house: :broom: :house_with_garden: