replace `//` => `/` in comments
microsoft/STL pull request #3208
Opened 2022-11-13 17:37 UTC by fsb4000

Sometimes we use `// ^^^ no workaround / workaround vvv` and sometimes `// ^^^ no workaround // workaround vvv`.
It looks like `/` is used more often. So I replaced all of `//` which I had found.
I used `//.+//` regexp and VS code.
Driven by: https://github.com/microsoft/STL/pull/3206#discussion_r1020755546

2022-11-14 08:58 UTC, SuperWig commented
Should this PR also settle on double arrows or one on each side i.e.
````
^^^ _HAS_CXX20 ^^^/ vvv !_HAS_CXX20 vvv
vs
^^^ _HAS_CXX20 / !_HAS_CXX20 vvv

2022-11-14 12:31 UTC, fsb4000 commented
Sure, and what do you like more?

2022-11-14 23:25 UTC, strega-nil-ms commented
I'll take a look at this once we discuss #351

2022-11-28 23:23 UTC, strega-nil-ms requested changes
Might as well standardize the location of the `^^^` and `vvv` as well; also do that through the rest of the file (probably should've just done one suggestion and then said that... sorry...)

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/bitset
> +#else // ^^^ _ITERATOR_DEBUG_LEVEL == 0 ^^^ / vvv _ITERATOR_DEBUG_LEVEL != 0 vvv
```suggestion
#else // ^^^ _ITERATOR_DEBUG_LEVEL == 0 / _ITERATOR_DEBUG_LEVEL != 0 vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/deque
> +#else // ^^^ _ITERATOR_DEBUG_LEVEL == 0 ^^^ / vvv _ITERATOR_DEBUG_LEVEL != 0 vvv
```suggestion
#else // ^^^ _ITERATOR_DEBUG_LEVEL == 0 / _ITERATOR_DEBUG_LEVEL != 0 vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/execution
> +#else // ^^^ _M_CEE ^^^ / vvv !_M_CEE vvv
```suggestion
#else // ^^^ _M_CEE / !_M_CEE vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/execution
> +#else // ^^^ _WIN64 ^^^ / vvv !_WIN64 vvv
```suggestion
#else // ^^^ _WIN64 / !_WIN64 vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/list
> +#else // ^^^ _ITERATOR_DEBUG_LEVEL == 2 ^^^ / vvv _ITERATOR_DEBUG_LEVEL != 2 vvv
```suggestion
#else // ^^^ _ITERATOR_DEBUG_LEVEL == 2 / _ITERATOR_DEBUG_LEVEL != 2 vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/new
> +#else // ^^^ supported hardware ^^^ / vvv unsupported hardware vvv
```suggestion
#else // ^^^ supported hardware / unsupported hardware vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/numeric
> +#else // ^^^ _HAS_CXX20 ^^^ / vvv !_HAS_CXX20 vvv
```suggestion
#else // ^^^ _HAS_CXX20 / !_HAS_CXX20 vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/numeric
> +#else // ^^^ _STD_VECTORIZE_WITH_FLOAT_CONTROL ^^^ / vvv !_STD_VECTORIZE_WITH_FLOAT_CONTROL vvv
```suggestion
#else // ^^^ _STD_VECTORIZE_WITH_FLOAT_CONTROL / !_STD_VECTORIZE_WITH_FLOAT_CONTROL vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/numeric
> +#else // ^^^ _HAS_CXX20 ^^^ / vvv !_HAS_CXX20 vvv
```suggestion
#else // ^^^ _HAS_CXX20 / !_HAS_CXX20 vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/numeric
> +#else // ^^^ _STD_VECTORIZE_WITH_FLOAT_CONTROL ^^^ / vvv !_STD_VECTORIZE_WITH_FLOAT_CONTROL vvv
```suggestion
#else // ^^^ _STD_VECTORIZE_WITH_FLOAT_CONTROL / !_STD_VECTORIZE_WITH_FLOAT_CONTROL vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/numeric
> +#else // ^^^ _HAS_CXX20 ^^^ / vvv !_HAS_CXX20 vvv
```suggestion
#else // ^^^ _HAS_CXX20 / !_HAS_CXX20 vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/numeric
> +#else // ^^^ _HAS_CXX20 ^^^ / vvv !_HAS_CXX20 vvv
```suggestion
#else // ^^^ _HAS_CXX20 / !_HAS_CXX20 vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/span
> +#else // ^^^ _ITERATOR_DEBUG_LEVEL >= 1 ^^^ / vvv _ITERATOR_DEBUG_LEVEL == 0 vvv
```suggestion
#else // ^^^ _ITERATOR_DEBUG_LEVEL >= 1 / _ITERATOR_DEBUG_LEVEL == 0 vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/span
> +#else // ^^^ _ITERATOR_DEBUG_LEVEL >= 1 ^^^ / vvv _ITERATOR_DEBUG_LEVEL == 0 vvv
```suggestion
#else // ^^^ _ITERATOR_DEBUG_LEVEL >= 1 / _ITERATOR_DEBUG_LEVEL == 0 vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/string
> +#else // ^^^ _WIN64 ^^^ / vvv !_WIN64 vvv
```suggestion
#else // ^^^ _WIN64 / !_WIN64 vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/vector
> +#else // ^^^ _ITERATOR_DEBUG_LEVEL == 0 ^^^ / vvv _ITERATOR_DEBUG_LEVEL != 0 vvv
```suggestion
#else // ^^^ _ITERATOR_DEBUG_LEVEL == 0 / _ITERATOR_DEBUG_LEVEL != 0 vvv
```

2022-11-28 23:23 UTC, strega-nil-ms commented on stl/inc/vector
> +#else // ^^^ _ITERATOR_DEBUG_LEVEL == 0 ^^^ / vvv _ITERATOR_DEBUG_LEVEL != 0 vvv
```suggestion
#else // ^^^ _ITERATOR_DEBUG_LEVEL == 0 / _ITERATOR_DEBUG_LEVEL != 0 vvv
```

2022-12-01 21:53 UTC, strega-nil-ms approved these changes

2022-12-05 14:57 UTC, StephanTLavavej approved these changes
Thanks for making this more consistent and easier to read! The changes to `<xcharconv_ryu.h>` are fine (they're in additions to the upstream code and don't represent unnecessary divergence).

2022-12-05 22:46 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

2022-12-06 22:25 UTC, merged

2022-12-06 22:26 UTC, StephanTLavavej commented
Thanks again for this consistency pass! :smile_cat: :tada: :100: