LWG-3833 Remove specialization `template<size_t N> struct formatter<const charT[N], charT>`
microsoft/STL pull request #3477
Opened 2023-02-17 21:48 UTC by mlemacio

Remove specialization `template<size_t N> struct formatter<const charT[N], charT>`

2023-02-17 21:54 UTC, StephanTLavavej commented
Thanks for the PR! Can you edit your PR description to add "Fixes #3426."? This is [special syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for GitHub that will link the issue to your PR. (It only takes effect in the PR description, not the title, and not later comments where issues can only be "mentioned".)

2023-02-17 22:02 UTC, mlemacio commented
Added to PR description

2023-02-17 23:41 UTC, strega-nil-ms approved these changes
LGTM!

2023-02-17 23:54 UTC, mlemacio commented
Yay! Are there any recommended resources on how to get more knowledgeable on the ecosystem so that I may contribute more? I consider myself a fairly seasoned user of C++ but this has been my first foray into open source.

2023-02-18 00:42 UTC, fsb4000 commented
You can watch the code reviews and notice what was wrong and don't do that in your PRs: https://www.youtube.com/playlist?list=PLReL099Y5nRffygixwNJhENbYxhuJL6Ei

2023-02-18 03:14 UTC, mlemacio commented
@fsb400 Just watched my first one in the playlist. Had a good time doing do. Thanks!

2023-02-18 13:47 UTC, mlemacio commented
@microsoft-github-policy-service agree

2023-02-18 14:37 UTC, fsb4000 commented
Something bad happened.
I think the correct commit is https://github.com/microsoft/STL/commit/384086c2d405d9aaa24ffa4fc76f80d2779a805a

2023-02-18 21:59 UTC, CaseyCarter requested changes
It appears that you've force-pushed the changes from your other PR atop this one.

2023-02-21 00:41 UTC, mlemacio commented
Sorry about that, should be fixed.

2023-02-21 05:23 UTC, CaseyCarter approved these changes

2023-02-21 12:58 UTC, StephanTLavavej approved these changes

2023-02-22 14:23 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

2023-02-23 01:44 UTC, merged

2023-02-23 01:45 UTC, StephanTLavavej commented
Thanks for implementing this LWG issue resolution, and congratulations on your first microsoft/STL commit! :heart_eyes_cat: :rocket: :tada:

This will ship in VS 2022 17.7 Preview 1.