P2609R3: Relaxing Ranges Just A Smidge
microsoft/STL pull request #3486
Opened 2023-02-20 16:05 UTC by JMazurkiewicz

Closes #3441.

Drive-by: reduced clang-format suppressed regions.

2023-02-20 16:43 UTC, JMazurkiewicz commented on stl/inc/xutility
> +
To be clear: `_Indirect_value_t<T>` in C++20 mode is same as `iter_value_t<T>&`, and only in C++23 mode we add this extra specialization.

2023-02-20 17:17 UTC, CaseyCarter requested changes

2023-02-20 17:17 UTC, CaseyCarter commented on tests/std/tests/P2609R3_relaxing_ranges_just_a_smidge/test.compile.pass.cpp
> +#include <iterator>
`<ranges>` must include `<iterator>` which must include `<concepts>`.
```suggestion
```

2023-02-20 18:23 UTC, JMazurkiewicz commented
/pr review

2023-02-20 21:57 UTC, CaseyCarter approved these changes

2023-02-20 21:57 UTC, CaseyCarter commented on stl/inc/yvals_core.h
> +// P2609R3 Relaxing Ranges Just A Smidge
These should be in the `_HAS_CXX20` section since they're both "always on".

2023-02-21 19:39 UTC, strega-nil-ms approved these changes
Looks good!

2023-02-21 23:52 UTC, StephanTLavavej approved these changes

2023-02-21 23:52 UTC, StephanTLavavej commented on stl/inc/xutility
> +    && common_reference_with<invoke_result_t<_Fn&, _Indirect_value_t<_It>>,
No change requested: I am uncomfortable with the drive-by reformatting here. The issue is that the reformatting is mixed with the semantic changes, which makes it harder to see what's going on. I would have preferred for this to be done in a separate PR. That said, it's not *too* complicated and we've already reviewed the changes, so let's leave it as-is.

2023-02-22 14:25 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

2023-02-23 02:01 UTC, merged