Implement LWG-3720 Restrict the valid types of arg-id for width and precision in std-format-spec
microsoft/STL pull request #3511
Opened 2023-02-28 06:39 UTC by fsb4000

Fixes #3425

2023-02-28 09:22 UTC, fsb4000 commented
```
std::format(L"{:*^{}}", 'a', '0');
```
'0' is type erasured as wchar_t, (`_Arg` == Char state)
 and later it passes the condition `_Standard_signed_or_unsigned_integer<_Ty>` because `wchar_t` == `unsigned short`
 
I'm not sure what we should do with  `/Zc:wchar_t-`

2023-02-28 13:06 UTC, fsb4000 commented
Thank @frederick-vs-ja !

Ok, I got you, so this code is accepted with `/Zc:wchar_t-`
```c++
std::wstring s = std::format(L"{:*^{}}\n", 'a', L'0');
```

and the lwg issue has the sentence: 
```
The following integral types are rejected by both libc++ and MSVC STL:

std::cout << std::format("{:*^{}}\n", 'a', L'0');
```

2023-02-28 14:46 UTC, CaseyCarter requested changes

2023-02-28 14:46 UTC, CaseyCarter commented on stl/inc/format
> +inline constexpr bool _Is_standard_signed_or_unsigned_integer =
This is missing four standard signed or unsigned integer types. I understand why, but I think we need a different name to avoid inadvertent reuse.

2023-02-28 15:14 UTC, CaseyCarter approved these changes

2023-02-28 19:23 UTC, strega-nil-ms approved these changes

2023-02-28 23:43 UTC, StephanTLavavej approved these changes

2023-02-28 23:45 UTC, StephanTLavavej commented
This works because we have machinery that promotes tiny types before they're seen here. The test coverage for `signed char` is sufficient.

2023-03-02 17:47 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

2023-03-03 23:40 UTC, merged

2023-03-03 23:41 UTC, StephanTLavavej commented
Thanks for the precise PR! :dart: :tada: :smile_cat: