`<numbers>`: Rework the implementation when concepts are missing
microsoft/STL pull request #3633
Opened 2023-04-07 03:14 UTC by frederick-vs-ja

In recent PR #3623 I noticed that the implementation of `<numbers>` when concepts are unavailable didn't seem correct enough. These variable templates are required to support possibly cv-qualified floating-point types due to `std::floating_point`, but the current concept-free implementation only supports cv-unqualified FP types.

This PR is adding test coverage for cv-qualified FP types, and rewriting the concept-free implementation. Technically, only the primary template is used, but I believe that the difference from the standard wording is unobservable.

Warning [C4197](https://learn.microsoft.com/sv-se/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4197?view=msvc-140) was encountered during local test. I think it's OK to only suppress that warning in testing, because it's already weird to use something that is both `constexpr` and `volatile`.

2023-04-07 16:55 UTC, strega-nil-ms requested changes
Minor change, but otherwise this looks great :)

2023-04-07 16:55 UTC, strega-nil-ms commented on stl/inc/numbers
> +    struct _Reject_primary_template {
Minor request - could this instead be `_Reject_invalid` or something along those lines? I think `_Reject_primary_template` is kind of a confusing name.

2023-04-08 20:11 UTC, StephanTLavavej approved these changes

2023-04-08 20:19 UTC, StephanTLavavej commented
Thanks, I think this is a nice improvement!

For the future, note that the non-concepts mode exists only for the STL's test suite. (By special agreement with the IDE team, we enable concepts code for actual IntelliSense, which doesn't need to deeply instantiate templates the way that `/BE` does.) 
While this PR eliminates enough squirrelliness :chipmunk: to be worthwhile, I think that any additional PRs would be less valuable. Instead of searching for additional non-concepts code to clean up, it would be better to spend cycles on #1621. (EDG is getting closer to fixing the blocking bugs for concepts, but last I heard, they could still use additional help getting truly minimized repros of the remaining issues.)

2023-04-11 22:21 UTC, strega-nil-ms approved these changes

2023-04-12 21:59 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

2023-04-14 03:19 UTC, merged

2023-04-14 03:25 UTC, StephanTLavavej commented
:1234: :1234: :1234:
===