Implement LWG-3843 `std::expected<T,E>::value() &` assumes `E` is copy constructible
microsoft/STL pull request #3737
Opened 2023-05-27 01:44 UTC by frederick-vs-ja

Per LWG-3843, `std::expected<int, std::unique_ptr<int>>{}.value()` needs to be rejected. But currently MSVC and Clang incorrectly accept it (DevCom-1638273 and LLVM-53224).

We also need to ensure that the `value() &` overload also treats `_Err` as a const lvalue on copy.

The mandating is missing in the standard wording in [[expected.void.obs]](https://eel.is/c++draft/expected.void.obs) currently, which is likely another LWG issue. I've mailed LWG chair for this.

2023-05-28 19:08 UTC, StephanTLavavej requested changes

2023-05-28 19:08 UTC, StephanTLavavej commented on stl/inc/expected
> +            "is_constructible_v<E, const E&&> must be true. N4950 [expected.object.obs]/11");
Implementing `is_constructible_v<E, const E&&>` with `is_move_constructible_v<_Err>` doesn't appear to be correct.

2023-05-29 07:17 UTC, StephanTLavavej approved these changes

2023-06-08 15:39 UTC, strega-nil-ms approved these changes

2023-06-14 19:05 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

2023-06-15 08:39 UTC, merged

2023-06-15 08:39 UTC, StephanTLavavej commented
Thanks for improving our conformance to the latest Working Paper as *expected*! :joy_cat: :tada: :rocket: