_Init_icu_functions should use memory_order_release and memory_order_consume rather than memory_order_acq_rel
microsoft/STL pull request #4288
Opened 2023-12-24 19:02 UTC by AtariDreams

As _Level, does not rely on _Api_level, we do not need an acquire operation, just a release one, unless the compare fails.

2024-01-03 23:24 UTC, CaseyCarter requested changes

2024-01-03 23:24 UTC, CaseyCarter commented on stl/src/tzdb.cpp
> +            _Level, _Icu_api_level::_Detecting, _STD memory_order_acq_rel, _STD memory_order_acquire)) {
[[atomics.types.operations]/23](https://eel.is/c++draft/atomics.types.operations#23) states "When only one `memory_order` argument is supplied, the value of [the first parameter] is `order`, and the value of [the second parameter] is `order` except that a value of `memory_order::acq_rel` shall be replaced by the value `memory_order::acquire` ..."

Consequently, this change is simply a longer way to spell what the existing code already does. I don't think the change is desirable.

2024-01-04 18:40 UTC, AtariDreams commented
@CaseyCarter Fixed!

2024-01-05 10:36 UTC, frederick-vs-ja commented
Hmm... I wonder what happened to your environment. Is there anything enforcing to force-push a single commit?

2024-01-09 00:30 UTC, CaseyCarter approved these changes

2024-01-10 21:17 UTC, StephanTLavavej approved these changes

2024-01-10 21:23 UTC, StephanTLavavej commented
Thanks, this is a good change, and is consistent with the very similar code in tzdb.cpp:

https://github.com/microsoft/STL/blob/87580ca91c1a34645d22f79f7640a13f68bb31c5/stl/src/tzdb.cpp#L57-L58

I'd still like to understand why you keep force-pushing and ignoring our requests to avoid doing so, but that shouldn't block merging this change. At least GitHub started providing a "Compare" button, although it's still harder to see what's changed over time than with the ordinary commits that everyone else uses.

2024-01-11 12:38 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

2024-01-11 23:24 UTC, merged

2024-01-11 23:24 UTC, StephanTLavavej commented
Thanks for improving the consistency of these atomic operations by avoiding full sequential consistency! :joy_cat: :radioactive: :tada: