Simplify control flow in `_Traits_find_MEOW_not_of`
microsoft/STL pull request #5006
Opened 2024-10-10 03:51 UTC by StephanTLavavej

This simplifies `_Traits_find_first_not_of` and `_Traits_find_last_not_of`, following the patterns in #4744 and #4934, which will make them easier to understand and easier to add vectorized codepaths. These are lossless transformations that don't affect behavior.

* Replace unnecessarily confusing `break`s with immediate `return`s.
  + Except in `_Traits_find_last_of`, which is being changed by #4934.
* Add a `return` instead of relying on fall-through.
  + This will simplify the following transformation.
* Flip `!_Matches._Mark` tests.
  + Both sides unconditionally return, allowing us to flip them. (One case is a forever loop where the only ways out are returns.)
* Transform "call self with `_Special=false`" to fall-through.
* Extract `_Elem`.
* Extract `_Hay_start`, `_Hay_end`.

2024-10-10 04:08 UTC, AlexGuteniev requested changes
I was going to do most of this in `not` vectorization PR, but maybe it is indeed cleaner not to mix.

As we no longer have tail calls here, remove `bool _Special = _Is_implementation_handled_char_traits<_Traits>` template parameter, as @frederick-vs-ja suggested and attempted.

2024-10-10 04:11 UTC, StephanTLavavej commented
> I was going to do most of this in not vectorization PR, but maybe it is indeed cleaner not to mix.

Yeah, it's difficult for me to follow two major changes combined, and I have a pretty high tolerance for review complexity.

> As we no longer have tail calls here, remove `bool _Special = _Is_implementation_handled_char_traits<_Traits>` template parameter, as @frederick-vs-ja suggested and attempted.

I agree that this should be done after #4934 and this PR land.

2024-10-10 15:37 UTC, CaseyCarter approved these changes
This is such a nice simplification, I thought I'd push another commit to do some early-return outdenting.

2024-10-10 15:37 UTC, CaseyCarter commented on stl/inc/__msvc_string_view.hpp
> +                return static_cast<size_t>(-1); // at beginning, no more chance for match
It seems odd to me that we're happy to early-return in this function, but we don't do so on line 631.

2024-10-10 15:37 UTC, CaseyCarter commented on stl/inc/__msvc_string_view.hpp
>              }
Ditto "early return on 650 could save us an indent".

2024-10-10 15:37 UTC, CaseyCarter commented on stl/inc/__msvc_string_view.hpp
>          const auto _Hay_start = _Haystack + _Start_at;
Ditto "early return on 722 could save us an indent".

2024-10-10 15:37 UTC, CaseyCarter commented on stl/inc/__msvc_string_view.hpp
>      if (_Start_at < _Hay_size) { // room for match, look for it
Ditto "Consider early return".

2024-10-10 15:37 UTC, CaseyCarter commented on stl/inc/__msvc_string_view.hpp
>      if (_Hay_size != 0) { // worth searching, do it
And one last recommendation for early-return.

2024-10-10 19:06 UTC, CaseyCarter approved these changes

2024-10-10 19:24 UTC, StephanTLavavej commented
:heart_eyes_cat: Looks purr to me!

2024-10-11 10:18 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

2024-10-12 04:10 UTC, CaseyCarter commented
A merge conflict? Couldn't be me.

2024-10-12 05:02 UTC, StephanTLavavej commented
Remember, I named you Casey "Conflict" Carter via office post-it note almost a decade ago! :dart: :100: :crystal_ball:

2024-10-12 12:49 UTC, merged