Unwrapping output iterators in range algorithms
microsoft/STL pull request #5015
Opened 2024-10-14 04:40 UTC by CaseyCarter

This completes the last bits of the iterator unwrapping design for Ranges algorithms.

Detailed commit-wise description:
* Expand `_Idl_distance` design for Ranges
  * Add `_Distance_unbounded` to represent the distance between an iterator and `unreachable_sentinel`.
  * `_Idl_distance` takes iterator/sentinel pairs in C++20 mode.
  * Add `_RANGES _Idl_distance(range)`, equivalent to `_STD _Idl_distance` but for `sized_range` instead of `sized_sentinel_for`.
  * Support integer-class difference types in `_Get_unwrapped_n`.

* Simplify `ranges::destroy_n`. Now that `_Get_unwrapped_n` supports integer-class difference types, we don't need to apply `_Algorithm_int_t` to `_Count`.

* Update operations on `_Idl_distance`s
  * Refactor `_Idl_dist_add`:
    * Use `if constexpr` dispatch instead of overloading.
    * `_Distance_unbounded` plus anything is `_Distance_unbounded`.
  * Implement `_Idl_dist_min` to compute the smaller of two `_Idl_distance`s.

* Rename Range algorithm output iterator parameters from `_Result` to `_Output`. This changes our convention. I think `_Output` is more appropriate than `_Result` for this purpose given that most algorithms produce more results than just the output sequence. This also makes `_Result` unambiguously available to refer to the return value of the algorithm which is consistent with our use of `_UResult` for intermediate unwrapped results.

* Unwrap outputs in `ranges::copy`

* Unwrap outputs in `ranges::copy_backward`

* Unwrap outputs in `ranges::copy_if`

* Unwrap outputs in `ranges::copy_n`

* Unwrap outputs in `ranges::merge`

* Unwrap outputs in `ranges::move`

* Unwrap outputs in `ranges::move_backward`

* Unwrap outputs in `ranges::replace_copy`

* Unwrap outputs in `ranges::replace_copy_if`

* Unwrap outputs in `ranges::reverse_copy`

* Unwrap outputs in `ranges::rotate_copy`

* Unwrap outputs in `ranges::sample`

* Unwrap outputs in `ranges::transform`

Fixes #893.

2024-10-14 17:58 UTC, StephanTLavavej requested changes

2024-10-15 01:47 UTC, CaseyCarter commented on stl/inc/__msvc_iter_core.hpp
> +constexpr bool _Integer_like = _Is_nonbool_integral<remove_cv_t<_Ty>>;
Corrected here and in the pre-existing definition of the `_Integer_like` concept.

2024-10-15 01:50 UTC, CaseyCarter commented on stl/inc/algorithm
> +                          && random_access_iterator<_Out>) { // FIXME: justify this with benchmarks
This is so huge I forgot about the FIXMEs. To be honest, I haven't earned the `_Transform_unary_n_unchecked` and `_Transform_binary_n_unchecked` functions at all, let alone these random-access special cases. I need benchmarking to justify them, which means they shouldn't be part of this change: yanking.

2024-10-15 02:44 UTC, StephanTLavavej approved these changes

2024-10-16 19:38 UTC, StephanTLavavej commented
I'm mirroring this to the MSVC-internal repo - please notify me if any further changes are pushed.

2024-10-17 05:48 UTC, merged

2024-10-17 05:49 UTC, StephanTLavavej commented
Thanks for this long-awaited improvement! :heart_eyes_cat: :magic_wand: :tada: